addons:
    apt:
        packages:
        - dos2unix
env:
    global:
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   TRAVIS_REPO_SLUG: dead-hosts/AdBlockID-Plus_realodix
    -   GIT_BRANCH: master
    -   secure: M2f8FadWqykey/hWY0Oln1nPBwsqMAYRyGpFfT62ZX7AxQItQ4k2iKecL2D237JNGaNTOLTrWvNA4+FcfkZN8svJdi9hfMVgF+PY8UqLTsArUhpEOgtkh6TfCszVPLfCpsIDznshVtsvl1KAQSnH3FwOai3BUtfn6izVN7tcBck6CnA2nJfU/8hPDbkx+rio609eLC6gqMyM93omaaCMiX39E4yr8dEaaepiMrQDbDeaeH/XikjB4lcABWXbx4IPs0Z8R85rSC/j6xGbRsuvQNQAQ3Ejar+4CkvArm0GmJzmV9iTY9z9Pq23vOU1cIK5gazmNmu3Qc1wX6aAZoF3wOpQvKyWMGA/FjH6Adlt8I5W42OVUjjWP2q3P5FgLi3MJdonxfuOqnA0jpqWASRY45Ly0mPlBj7G208bsH7+lpbaR1wWiJD2uhSCbHTK2R3wqPHrKplgFbUdjk5QgfdF2kZxKw9fu/1k9GU1iqf00pHSzP3SZ5iFasf75wOPWI7HLYqD0hehvHazFP0ZhGSgz1BRtrsly4dJujYXIC9j3CWhzKYPGSRMoH3K4+rNGf4YEH0ItW5XoeqLipDErm5unI5/xsvrdfuvGuQqdfqAwsXuidmd/dd4Nx+BTVwLBfuS8XjPjyXDPSeHrXuf/H37pv8Xnxxs1SHVA4GKd7OzcIc=
    matrix:
    - PYTHON_VERSION="3.7.3"
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install git+https://github.com/realodix/infrastructure-launcher#egg=dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@funilrys.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
sudo: required
